# @host = localhost:2266
@host = 192.168.0.136:2266

### Check server status
GET http://{{host}}/

###

### Open a YouTube video
GET http://{{host}}/?url=https://www.youtube.com/watch?v=2fONEL2Udwo

###

### Open a YouTube short link
GET http://{{host}}/?url=https://youtu.be/dQw4w9WgXcQ

###

### Play another video (switches in same window)
GET http://{{host}}/?url=https://www.youtube.com/watch?v=jNQXAC9IVRw

###

### Open a non-YouTube URL
GET http://{{host}}/?url=https://www.google.com

###

### Set volume to 50%
GET http://{{host}}/volume?level=50

###

### Set volume to max
GET http://{{host}}/volume?level=100

###

### Mute volume
GET http://{{host}}/volume?level=0

###

### Set system volume to max (Linux/macOS)
GET http://{{host}}/volume?level=100&system=true

###

### Set system volume to 50% (Linux/macOS)
GET http://{{host}}/volume?level=50&system=true

###

### Toggle mute
GET http://{{host}}/mute

###

### Pause video
GET http://{{host}}/pause

###

### Resume video
GET http://{{host}}/resume

###

### Toggle fullscreen
GET http://{{host}}/fullscreen

###

### Close the media window
GET http://{{host}}/?url=KILL_app

###

### POST request
POST http://{{host}}/
Content-Type: application/json

{
  "message": "hello from client"
}
