# @host = localhost:2266
@host = 192.168.0.136:2266

### Check server status
GET http://{{host}}/

###

### Open a YouTube video
GET http://{{host}}/?url=https://www.youtube.com/watch?v=2fONEL2Udwo

###

### Open a YouTube short link
GET http://{{host}}/?url=https://youtu.be/dQw4w9WgXcQ

###

### Play another video (switches in same window)
GET http://{{host}}/?url=https://www.youtube.com/watch?v=jNQXAC9IVRw

###

### Open a non-YouTube URL
GET http://{{host}}/?url=https://www.google.com

###

### Set volume to 50%
GET http://{{host}}/volume?level=50

###

### Set volume to max
GET http://{{host}}/volume?level=100

###

### Mute volume
GET http://{{host}}/volume?level=0

###

### Set system volume to max (Linux/macOS)
GET http://{{host}}/volume?level=100&system=true

###

### Set system volume to 50% (Linux/macOS)
GET http://{{host}}/volume?level=50&system=true

###

### Toggle mute
GET http://{{host}}/mute

###

### Pause video
GET http://{{host}}/pause

###

### Resume video
GET http://{{host}}/resume

###

### Toggle fullscreen
GET http://{{host}}/fullscreen

###

### Close the media window
GET http://{{host}}/?url=KILL_app

###

### POST request
POST http://{{host}}/
Content-Type: application/json

{
  "message": "hello from client"
}

###

### Create a cron job (hits an API every 30 seconds)
POST http://{{host}}/cron
Content-Type: application/json

{
  "name": "Health check",
  "url": "https://httpbin.org/get",
  "method": "GET",
  "intervalSeconds": 30
}

###

### Create a cron job with POST method and body
POST http://{{host}}/cron
Content-Type: application/json

{
  "name": "Post data every minute",
  "url": "https://httpbin.org/post",
  "method": "POST",
  "body": { "key": "value" },
  "intervalSeconds": 60
}

###

### Batch create cron jobs (simple array of URLs, default 10s interval)
POST http://{{host}}/cron/batch
Content-Type: application/json

{
  "urls": [
    "https://httpbin.org/get",
    "https://httpbin.org/ip",
    "https://httpbin.org/user-agent"
  ]
}

###

### Batch create with custom intervals per URL
POST http://{{host}}/cron/batch
Content-Type: application/json

{
  "urls": [
    { "url": "https://httpbin.org/get", "intervalSeconds": 15 },
    { "url": "https://httpbin.org/ip", "intervalSeconds": 30 },
    "https://httpbin.org/user-agent"
  ],
  "intervalSeconds": 20
}

###

### List all cron jobs
GET http://{{host}}/cron

###

### Delete a cron job (replace 1 with actual job id)
DELETE http://{{host}}/cron/1

###

### Delete all cron jobs
DELETE http://{{host}}/cron
